"""Pipeline orchestration for the local meeting event analysis MVP.

The orchestrator keeps stage wiring and artifact persistence in one place while
leaving heavy work to dedicated modules.  Parsing, extraction, embedding,
grouping, merging, timeline building, and report writing should remain in their
own packages.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from meeting_summarizer.agents.event_merger import EventMerger
from meeting_summarizer.agents.llm_client import LLMClient, build_llm_client
from meeting_summarizer.agents.timeline_builder import TimelineBuilder
from meeting_summarizer.config import AppConfig, ensure_output_directories
from meeting_summarizer.schemas import EventCase
from meeting_summarizer.storage.json_store import JsonStore
from meeting_summarizer.utils.logging import get_logger

LOGGER = get_logger(__name__)


class PipelineError(RuntimeError):
    """Raised when an orchestrated pipeline stage cannot complete."""


@dataclass(slots=True)
class PipelineRunResult:
    """Paths and counts produced by the event-case merge pipeline stage."""

    event_cases_path: Path
    event_case_count: int


class MeetingEventPipeline:
    """Coordinate pipeline stages without owning stage internals.

    The current executable stage starts from saved candidate/group artifacts and
    finishes step 9 of the MVP pipeline:

    ``event_candidates.json`` + ``candidate_groups.json``
    -> LLM event merge
    -> LLM timeline organization
    -> ``event_cases.json``
    """

    def __init__(
        self,
        config: AppConfig,
        *,
        llm_client: LLMClient | None = None,
        store: JsonStore | None = None,
    ) -> None:
        self.config = config
        self.llm_client = llm_client or build_llm_client(config)
        self.store = store or JsonStore(config.data_dir)
        self.event_merger = EventMerger(self.llm_client)
        self.timeline_builder = TimelineBuilder(self.llm_client)

    def merge_event_cases_from_artifacts(self) -> PipelineRunResult:
        """Load candidates/groups, merge cases, build timelines, and save JSON.

        This method intentionally does not re-read raw meeting text.  It starts
        from structured artifacts generated by earlier stages and writes the
        canonical final case artifact at ``data/cases/event_cases.json``.
        """

        ensure_output_directories(self.config)
        self.store.ensure_structure()

        candidates = self.store.load_event_candidates()
        groups = self.store.load_candidate_groups()
        if not candidates:
            raise PipelineError("No event candidates found for event-case merge.")
        if not groups:
            raise PipelineError("No candidate groups found for event-case merge.")

        LOGGER.info(
            "Merging %s candidate group(s) from %s candidate(s).",
            len(groups),
            len(candidates),
        )
        merged_cases = self.event_merger.merge_groups(groups, candidates)
        event_cases = self.timeline_builder.build_for_cases(merged_cases)
        event_cases_path = self.store.save_event_cases(event_cases)

        LOGGER.info(
            "Saved %s event case(s) to %s.",
            len(event_cases),
            event_cases_path,
        )
        return PipelineRunResult(
            event_cases_path=event_cases_path,
            event_case_count=len(event_cases),
        )

    def save_event_cases(self, event_cases: list[EventCase]) -> PipelineRunResult:
        """Persist already-built event cases through the canonical JSON store."""

        if not event_cases:
            raise PipelineError("No event cases were provided for saving.")
        ensure_output_directories(self.config)
        self.store.ensure_structure()
        event_cases_path = self.store.save_event_cases(event_cases)
        return PipelineRunResult(
            event_cases_path=event_cases_path,
            event_case_count=len(event_cases),
        )
